version: "3.8"

services:
  redis:
    container_name: purplebox-redis
    image: redis:latest
    ports:
      - '6379:6379'

  postgres:
    container_name: purplebox-postgres
    build:
      context: ./../
      dockerfile: ./docker/postgres/Dockerfile
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw

  php-fpm:
    container_name: purplebox-php
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    environment:
      APP_SERVER: ${APP_SERVER}
      API_PROJECT_DIR: ${API_PROJECT_DIR}
      CMS_PROJECT_DIR: ${CMS_PROJECT_DIR}
      PHP_IDE_CONFIG: "serverName=Docker"
      #DATABASE_URL: "postgresql://app:!ChangeMe!@127.0.0.1:5432/app?serverVersion=15&charset=utf8"
      POSTGRES_DB: ${POSTGRES_DB}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      WEB_PROJECT_DOMAIN: ${WEB_PROJECT_DOMAIN}
      PUBLIC_UPLOADS_PATH: ${PUBLIC_UPLOADS_PATH}
      PUBLIC_UPLOADS_DIR: ${PUBLIC_UPLOADS_DIR}
      API_PROJECT_DOMAIN: ${API_PROJECT_DOMAIN}
      API_PROJECT_ROUTE_PREFIX: ${API_PROJECT_ROUTE_PREFIX}
      API_ASSETS_PATH: ${API_ASSETS_PATH}
      CMS_ASSETS_PATH: ${CMS_ASSETS_PATH}
      CMS_PROJECT_ROUTE_PREFIX: ${CMS_PROJECT_ROUTE_PREFIX}
      CMS_PROJECT_DOMAIN: ${CMS_PROJECT_DOMAIN}
      CDN_ENABLED: ${CDN_ENABLED}
      CDN_DOMAIN: ${CDN_DOMAIN}
      FFMPEG_BINARIES_PATH: ${FFMPEG_BINARIES_PATH}
      FFPROBE_BINARIES_PATH: ${FFPROBE_BINARIES_PATH}
      MAILER_DSN: ${MAILER_DSN}
      EMAIL: ${EMAIL}
      EMAIL_NAME: ${EMAIL_NAME}
      EMAIL_SUPPORT: ${EMAIL_SUPPORT}
      OAUTH_GOOGLE_CLIENT_ID: ${OAUTH_GOOGLE_CLIENT_ID}
      OAUTH_GOOGLE_CLIENT_SECRET: ${OAUTH_GOOGLE_CLIENT_SECRET}
      AWS_KEY: ${AWS_KEY}
      AWS_SECRET: ${AWS_SECRET}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      REDIS_URL: ${REDIS_URL}
      REDIS_IS_ENABLE: ${REDIS_IS_ENABLE}
      REDIS_QUEUE_IS_ENABLE: ${REDIS_QUEUE_IS_ENABLE}
      JWT_TOKEN_TTL: ${JWT_TOKEN_TTL}
      JWT_AUTH_PASS: ${JWT_AUTH_PASS}
      REFRESH_TOKEN_TTL: ${REFRESH_TOKEN_TTL}
    volumes:
#      - /var/www/vendor/
      - ./../sources/:/var/www/sources/
    depends_on:
      - postgres

  nginx:
    container_name: purplebox-nginx
    build:
      context: ./nginx
#    image: nginx:latest
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ..:/var/www:rw
    depends_on:
      - php-fpm

#  mailer:
#    image: schickling/mailcatcher
#    ports: ["1025", "1080"]

volumes:
  db_data:
